// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaCmL7lWYQxxpaiwlucChy26HZ2MmpzkY',
    appId: '1:797664372754:web:961979d6361bbb190a10cb',
    messagingSenderId: '797664372754',
    projectId: 'paned-225e3',
    authDomain: 'paned-225e3.firebaseapp.com',
    storageBucket: 'paned-225e3.firebasestorage.app',
    measurementId: 'G-ZP01MLHPVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvlkY9qki4t4hC5YrCxsxBlyWy2vaSoS8',
    appId: '1:797664372754:android:684111a923a7898d0a10cb',
    messagingSenderId: '797664372754',
    projectId: 'paned-225e3',
    storageBucket: 'paned-225e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8eWKO0KO5s5fy7Sqng6AuO-dTETYT49M',
    appId: '1:797664372754:ios:eafcc3dc36fa6fe90a10cb',
    messagingSenderId: '797664372754',
    projectId: 'paned-225e3',
    storageBucket: 'paned-225e3.firebasestorage.app',
    iosBundleId: 'com.paned.app.panedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8eWKO0KO5s5fy7Sqng6AuO-dTETYT49M',
    appId: '1:797664372754:ios:eafcc3dc36fa6fe90a10cb',
    messagingSenderId: '797664372754',
    projectId: 'paned-225e3',
    storageBucket: 'paned-225e3.firebasestorage.app',
    iosBundleId: 'com.paned.app.panedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaCmL7lWYQxxpaiwlucChy26HZ2MmpzkY',
    appId: '1:797664372754:web:f1006ae0c38426c30a10cb',
    messagingSenderId: '797664372754',
    projectId: 'paned-225e3',
    authDomain: 'paned-225e3.firebaseapp.com',
    storageBucket: 'paned-225e3.firebasestorage.app',
    measurementId: 'G-1CHLK9Y39F',
  );
}
